apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consul
    spec:
      containers:
      - image: consul:1.5.1
        name: gokitconsul-consul
        ports:
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 8600
        resources: {}
      restartPolicy: Always
status: {}
