apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
  - name: "8000"
    nodePort: 32000
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: "8001"
    nodePort: 32001
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    io.kompose.service: gateway
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
