apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - env:
        - name: QS_CONSULT_HOST
          value: consul
        - name: QS_CONSULT_PORT
          value: "8500"
        - name: QS_GATEWAY_GRPC_PORT
          value: "8001"
        - name: QS_GATEWAY_HTTP_PORT
          value: "8000"
        - name: QS_GATEWAY_LOG_LEVEL
          value: info
        - name: QS_GATEWAY_RETRY_MAX
          value: "3"
        - name: QS_GATEWAY_RETRY_TIMEOUT
          value: "500"
        - name: QS_GATEWAY_SERVER_CERT
          value: /ssl/localhost+3.pem
        - name: QS_GATEWAY_SERVER_KEY
          value: /ssl/localhost+3-key.pem
        - name: QS_ZIPKIN_V2_URL
          value: http://zipkin:9411/api/v2/spans
        image: {{ .Values.gateway.image }}
        name: gokitconsul-gateway
        ports:
        - containerPort: 8000
        - containerPort: 8001
        resources: {}
        volumeMounts:
        - mountPath: /ssl/localhost+3.pem
          name: secret-volume
          subPath: gateway-server.crt
        - mountPath: /ssl/localhost+3-key.pem
          name: secret-volume
          subPath: gateway-server.key
      restartPolicy: Always
      volumes:
      - name: secret-volume
        secret:
          secretName: gokitconsul-secret
status: {}
