apiVersion: v1
kind: Secret
metadata:
  name: gokitconsul-secret
data:
  gateway-server.crt: {{.Files.Get "static/ssl/localhost+3.pem" | b64enc }}
  gateway-server.key: {{.Files.Get "static/ssl/localhost+3-key.pem" | b64enc }}
type: Opaque